### PR TITLE
Update ReadAllNotificationsButton.plugin.js

### PR DESCRIPTION
**Pull request by austinbabe**
Update ReadAllNotificationsButton.plugin.js for center the button.
For adding these two lines.
```
display: flex;
justify-content: center;  
```

### CODE REVIEW

**Comment by austinbabe** [comment]
the other lines are changed by prettier(formatter).

**Comment by Maximilian1271** [comment]
Pardon my ignorance, but what exactly does this PR aim to fix?
As i currently see it, the "Read all" button from master is perfectly centered.

Just to be save, i forked your fork and compared the button as it currently is in master with your fork's master (including this commit), took a screenshot with the unmodified ReadAllNotificationsButton.plugin.js active and took a screenshot with your changes. Visually, i couldn't spot anything different, so i put both screenshots into adobe photoshop and set the blend mode to "Difference". This is the resulting difference between the two .js':

image

As you can see, there's nothing to see.

I mean, by all means, setting "display: flex; justify-content: center;" isn't going to break anything.. But frankly, i don't really see why this PR is necessary at all. Aside, you should probably not prettify your commit like that. It might be more legible that way, and it may even be syntactically more "correct", but this is just making it more difficult to compare your branch with master.
Also, who is to say that your "pretty" version does not conflict with, perhaps, the linter which the repo is using?

However please correct me if i'm wrong.

**Comment by austinbabe** [comment]
Because of the lint plugins, this PR is closed.

**Comment by Maximilian1271** [comment]
> Because of the lint plugins, this PR is closed.

lol. I didn't even say the repo is definitely using a linter. I was merely suggesting it could use one and that prettifying the code could mess with something like that. But hmmkay

**Comment by austinbabe** [comment]
> > Because of the lint plugins, this PR is closed.
> 
> 
> 
> lol. I didn't even say the repo is definitely using a linter. I was merely suggesting it could use one and that prettifying the code could mess with something like that. But hmmkay

> As I mentioned , 'prettier' is a linter. It's not adjective but noun.

**Pull request closed without merging**
