### PR TITLE
 Enhance Translator Plugin to Differentiate Private Messages from Public Channels

### PR DESCRIPTION
**Pull request by Rick-Sanchez-C**
**Overview**
This pull request enhances the Translator plugin by adding functionality to differentiate between private messages (DMs) and public channels when configuring translation settings.

**Changes Made**

1. **Added Differentiation Logic:**
   - Updated the `getLanguageChoice` function to check if the channel is a private message and retrieve the language choice accordingly.
   - Modified the `saveLanguageChoice` function to save settings separately for private messages and guild channels.

2. **Updated UI Components:**
   - Ensured the translation button and settings panel reflect changes based on the type of channel.

**Testing**
- Tested the plugin with:
  - Direct messages (DMs)
  - Group DMs
  - Public channels in a guild
- Verified that the translation settings are correctly applied and stored for each type of channel.

**Motivation**
These changes aim to improve user experience by allowing distinct translation settings for private and public conversations, thereby providing more granular control over the plugin's functionality.

**Response to the Question**

*What exactly does this change? You can already change the language choices on a server and channel level, why add a DM check?*

By default, the plugin's translation settings work at the server and channel level, and globally for all DMs. However, this update introduces the capability to identify each individual or group DM and save the configuration individually. This means that users can now set and retain different translation preferences for each private conversation, whether it’s a one-on-one DM or a group DM, rather than applying the same setting across all DMs. This provides a more personalized and flexible user experience.

**Note:** The previous pull request (https://github.com/mwittrien/BetterDiscordAddons/pull/2689) was closed due to a lack of response as I did not receive the notification.

### CODE REVIEW

**Comment by mwittrien** [comment]
_By default, the plugin's translation settings work at the server and channel level, and globally for all DMs. However, this update introduces the capability to identify each individual or group DM and save the configuration individually. This means that users can now set and retain different translation preferences for each private conversation, whether it’s a one-on-one DM or a group DM, rather than applying the same setting across all DMs. This provides a more personalized and flexible user experience._

But that's not true? You can easily tell the plugin to only change the language settings by clicking the "Lock" icon

**Comment by mwittrien** [comment]
You need to click it twice so its red

Yellow means guild specific

Red means channel specific

Since all DMs together are handled like a guild and each indiviual DM like a channel

**Comment by Rick-Sanchez-C** [comment]
Will do a test today to see if it works for me and send some ss

**Comment by Rick-Sanchez-C** [comment]
Looks like now it is working, not sure what happened the day that I was testing it and didnt work properly then it is not needed.

**Pull request closed without merging**
