### PR TITLE
More like that

### PR DESCRIPTION
**Pull request by Justman10000**
The one if line is nonsensical, otherwise the standard path cannot be overwritten! Tried it with my code and it works!

### CODE REVIEW

**Comment by mwittrien** [comment]
You can change the path in the list in the settings

**Comment by Justman10000** [comment]
> 
> 
> You can change the path in the list in the settings

Where?

**Comment by mwittrien** [comment]
In the plugin settings in your locations list

**Comment by Justman10000** [comment]
> 
> 
> In the plugin settings in your locations list

Above is a screen of it... How is that supposed to work? The existing line is deactivated!

**Comment by mwittrien** [comment]
Guess i forgot to upload the version where the input field wasnt disabled

**Comment by mwittrien** [comment]
Just changed it

**Comment by Justman10000** [comment]
> 
> 
> Guess i forgot to upload the version where the input field wasnt disabled

Yeah 😅

**Pull request closed without merging**
